import { Month, LearningItem } from './roadmapTypes';

// Helper to create learning items
function createItem(
  title: string,
  type: LearningItem['type'],
  youtubeKeyword?: string,
  count?: number
): LearningItem {
  return {
    id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    title,
    type,
    completed: false,
    url: youtubeKeyword ? `https://www.youtube.com/results?search_query=${encodeURIComponent(youtubeKeyword)}` : undefined,
    count,
    currentCount: 0,
  };
}

export const roadmapData: Month[] = [
  {
    id: 'month-1',
    monthNumber: 1,
    title: 'Foundations & JavaScript',
    goal: 'Master JS, web basics, Git, and problem-solving.',
    completed: false,
    weeks: [
      {
        id: 'month-1-week-1',
        weekNumber: 1,
        title: 'Web & Git Basics',
        completed: false,
        items: [
          createItem('HTTP vs HTTPS', 'topic'),
          createItem('DNS', 'topic'),
          createItem('Request/Response cycle', 'topic'),
          createItem('How does the web work', 'youtube', 'How does the web work'),
          createItem('HTTP vs HTTPS explained', 'youtube', 'HTTP vs HTTPS explained'),
          createItem('DNS explained for beginners', 'youtube', 'DNS explained for beginners'),
          createItem('Git init, add, commit, push, branch', 'topic'),
          createItem('Git & GitHub tutorial for beginners', 'youtube', 'Git & GitHub tutorial for beginners'),
          createItem('Create GitHub repo, push first file', 'project'),
          createItem('GitHub tutorial for beginners 2026', 'youtube', 'GitHub tutorial for beginners 2026'),
        ],
      },
      {
        id: 'month-1-week-2',
        weekNumber: 2,
        title: 'JS Core',
        completed: false,
        items: [
          createItem('Variables, Loops, Functions', 'topic'),
          createItem('Arrays, Objects, Strings', 'topic'),
          createItem('JavaScript basics for beginners', 'youtube', 'JavaScript basics for beginners'),
          createItem('JavaScript ES6 tutorial', 'youtube', 'JavaScript ES6 tutorial'),
          createItem('Solve 10 basic problems', 'practice', undefined, 10),
          createItem('JavaScript coding interview problems beginners', 'youtube', 'JavaScript coding interview problems beginners'),
        ],
      },
      {
        id: 'month-1-week-3',
        weekNumber: 3,
        title: 'Modern JS',
        completed: false,
        items: [
          createItem('Arrow Functions', 'topic'),
          createItem('Template Literals', 'topic'),
          createItem('Async/Await', 'topic'),
          createItem('Promises', 'topic'),
          createItem('Try/Catch', 'topic'),
          createItem('JavaScript ES6 features', 'youtube', 'JavaScript ES6 features'),
          createItem('JavaScript Async Await tutorial', 'youtube', 'JavaScript Async Await tutorial'),
          createItem('JavaScript Promises tutorial', 'youtube', 'JavaScript Promises tutorial'),
          createItem('Solve 10 medium JS problems', 'practice', undefined, 10),
        ],
      },
      {
        id: 'month-1-week-4',
        weekNumber: 4,
        title: 'DSA Logic',
        completed: false,
        items: [
          createItem('Stack', 'topic'),
          createItem('Queue', 'topic'),
          createItem('Linked List', 'topic'),
          createItem('Linear Search', 'topic'),
          createItem('Bubble Sort', 'topic'),
          createItem('Data Structures JavaScript', 'youtube', 'Data Structures JavaScript'),
          createItem('JavaScript algorithms for beginners', 'youtube', 'JavaScript algorithms for beginners'),
          createItem('Stack Queue Linked List JS', 'youtube', 'Stack Queue Linked List JS'),
          createItem('Solve 10 logic problems', 'practice', undefined, 10),
          createItem('Solve 5 medium Array/String problems', 'practice', undefined, 5),
        ],
      },
    ],
  },
  {
    id: 'month-2',
    monthNumber: 2,
    title: 'First Backend + TypeScript',
    goal: 'Build first API, learn MongoDB, TypeScript basics.',
    completed: false,
    weeks: [
      {
        id: 'month-2-week-1',
        weekNumber: 1,
        title: 'Node.js & Express',
        completed: false,
        items: [
          createItem('Node.js runtime', 'topic'),
          createItem('Modules', 'topic'),
          createItem('Express basics', 'topic'),
          createItem('Node.js crash course 2026', 'youtube', 'Node.js crash course 2026'),
          createItem('Express.js tutorial for beginners', 'youtube', 'Express.js tutorial for beginners'),
          createItem('Build Hello World API', 'project'),
          createItem('Test with Postman', 'topic'),
          createItem('Node.js REST API tutorial', 'youtube', 'Node.js REST API tutorial'),
          createItem('Postman API testing tutorial', 'youtube', 'Postman API testing tutorial'),
        ],
      },
      {
        id: 'month-2-week-2',
        weekNumber: 2,
        title: 'MongoDB & Auth',
        completed: false,
        items: [
          createItem('MongoDB CRUD with Mongoose', 'topic'),
          createItem('Schemas, Models', 'topic'),
          createItem('MongoDB tutorial for beginners', 'youtube', 'MongoDB tutorial for beginners'),
          createItem('Mongoose CRUD Node.js', 'youtube', 'Mongoose CRUD Node.js'),
          createItem('JWT authentication', 'topic'),
          createItem('bcrypt password hashing', 'topic'),
          createItem('JWT authentication Node.js tutorial', 'youtube', 'JWT authentication Node.js tutorial'),
          createItem('bcrypt password hashing Node.js', 'youtube', 'bcrypt password hashing Node.js'),
          createItem('Bookstore API with registration/login + CRUD', 'project'),
        ],
      },
      {
        id: 'month-2-week-3',
        weekNumber: 3,
        title: 'TypeScript Basics',
        completed: false,
        items: [
          createItem('Types, Interfaces', 'topic'),
          createItem('Generics', 'topic'),
          createItem('Strict Mode', 'topic'),
          createItem('TypeScript tutorial for beginners 2026', 'youtube', 'TypeScript tutorial for beginners 2026'),
          createItem('TypeScript strict mode explained', 'youtube', 'TypeScript strict mode explained'),
          createItem('Refactor Bookstore API to TypeScript', 'project'),
        ],
      },
      {
        id: 'month-2-week-4',
        weekNumber: 4,
        title: 'Reality Check Coding Challenges',
        completed: false,
        items: [
          createItem('Inventory API - prevent selling if stock < requested', 'assignment'),
          createItem('Node.js inventory management project', 'youtube', 'Node.js inventory management project'),
          createItem('Simple Auth System - admin-only dashboard', 'assignment'),
          createItem('Node.js role based authentication tutorial', 'youtube', 'Node.js role based authentication tutorial'),
        ],
      },
    ],
  },
  {
    id: 'month-3',
    monthNumber: 3,
    title: 'SQL & Prisma ORM',
    goal: 'Master SQL, Prisma, and Next.js integration.',
    completed: false,
    weeks: [
      {
        id: 'month-3-week-1',
        weekNumber: 1,
        title: 'SQL & RDBMS',
        completed: false,
        items: [
          createItem('ER Diagrams', 'topic'),
          createItem('Normalization', 'topic'),
          createItem('SQL queries (SELECT, INSERT, UPDATE, DELETE)', 'topic'),
          createItem('PostgreSQL tutorial for beginners', 'youtube', 'PostgreSQL tutorial for beginners'),
          createItem('ER diagrams tutorial', 'youtube', 'ER diagrams tutorial'),
          createItem('SQL normalization explained', 'youtube', 'SQL normalization explained'),
        ],
      },
      {
        id: 'month-3-week-2',
        weekNumber: 2,
        title: 'Prisma ORM',
        completed: false,
        items: [
          createItem('Prisma Schema', 'topic'),
          createItem('Migrations', 'topic'),
          createItem('Relations (1:1, 1:N, N:N)', 'topic'),
          createItem('Prisma ORM tutorial', 'youtube', 'Prisma ORM tutorial'),
          createItem('Prisma Node.js tutorial', 'youtube', 'Prisma Node.js tutorial'),
          createItem('Connect Node.js backend to PostgreSQL and seed data', 'project'),
        ],
      },
      {
        id: 'month-3-week-3',
        weekNumber: 3,
        title: 'Next.js Bridge',
        completed: false,
        items: [
          createItem('App Router', 'topic'),
          createItem('Server Actions', 'topic'),
          createItem('Server Components', 'topic'),
          createItem('API Routes', 'topic'),
          createItem('Next.js 14 tutorial', 'youtube', 'Next.js 14 tutorial'),
          createItem('Next.js API routes tutorial', 'youtube', 'Next.js API routes tutorial'),
          createItem('Small Blog App (Next.js + Prisma)', 'project'),
        ],
      },
      {
        id: 'month-3-week-4',
        weekNumber: 4,
        title: 'Advanced CRUD & Architecture',
        completed: false,
        items: [
          createItem('Service-Controller pattern', 'topic'),
          createItem('Modular folder structure', 'topic'),
          createItem('Node.js service controller architecture', 'youtube', 'Node.js service controller architecture'),
          createItem('Node.js project structure best practices', 'youtube', 'Node.js project structure best practices'),
        ],
      },
    ],
  },
  {
    id: 'month-4',
    monthNumber: 4,
    title: 'Capstone Project 1 – DeshDoor',
    goal: 'Build a complete hyperlocal marketplace with multi-role auth.',
    completed: false,
    weeks: [
      {
        id: 'month-4-week-1',
        weekNumber: 1,
        title: 'Project Setup & Auth',
        completed: false,
        items: [
          createItem('Next.js 14 setup', 'topic'),
          createItem('NextAuth multi-role authentication', 'topic'),
          createItem('Next.js NextAuth multi role authentication', 'youtube', 'Next.js NextAuth multi role authentication'),
        ],
      },
      {
        id: 'month-4-week-2',
        weekNumber: 2,
        title: 'Core Logic',
        completed: false,
        items: [
          createItem('Service booking logic', 'topic'),
          createItem('Relational schema (User → Booking → Service)', 'topic'),
          createItem('Next.js booking system tutorial', 'youtube', 'Next.js booking system tutorial'),
          createItem('Prisma relations tutorial', 'youtube', 'Prisma relations tutorial'),
        ],
      },
      {
        id: 'month-4-week-3',
        weekNumber: 3,
        title: 'Dashboard',
        completed: false,
        items: [
          createItem('Provider panel', 'topic'),
          createItem('Admin panel', 'topic'),
          createItem('CRUD operations', 'topic'),
          createItem('Next.js admin panel tutorial', 'youtube', 'Next.js admin panel tutorial'),
          createItem('React dashboard tutorial', 'youtube', 'React dashboard tutorial'),
        ],
      },
      {
        id: 'month-4-week-4',
        weekNumber: 4,
        title: 'Deployment & Documentation',
        completed: false,
        items: [
          createItem('Deploy DB to Neon/Supabase', 'project'),
          createItem('Deploy app to Vercel', 'project'),
          createItem('Swagger/Postman docs', 'topic'),
          createItem('Vercel deployment tutorial Next.js', 'youtube', 'Vercel deployment tutorial Next.js'),
          createItem('Supabase tutorial', 'youtube', 'Supabase tutorial'),
          createItem('Swagger tutorial for Node.js', 'youtube', 'Swagger tutorial for Node.js'),
        ],
      },
    ],
  },
  {
    id: 'month-5',
    monthNumber: 5,
    title: 'Capstone Project 2 – RideShare Backend',
    goal: 'Build high-performance backend with microservices, Redis, and Docker.',
    completed: false,
    weeks: [
      {
        id: 'month-5-week-1',
        weekNumber: 1,
        title: 'Setup Microservices & Redis',
        completed: false,
        items: [
          createItem('Node.js microservices', 'topic'),
          createItem('Redis caching', 'topic'),
          createItem('Node.js microservices tutorial', 'youtube', 'Node.js microservices tutorial'),
          createItem('Redis Node.js tutorial', 'youtube', 'Redis Node.js tutorial'),
        ],
      },
      {
        id: 'month-5-week-2',
        weekNumber: 2,
        title: 'Complex Logic',
        completed: false,
        items: [
          createItem('Mock driver GPS tracking', 'topic'),
          createItem('Caching active drivers in Redis', 'topic'),
          createItem('Node.js real time tracking tutorial', 'youtube', 'Node.js real time tracking tutorial'),
          createItem('Redis caching tutorial Node.js', 'youtube', 'Redis caching tutorial Node.js'),
        ],
      },
      {
        id: 'month-5-week-3',
        weekNumber: 3,
        title: 'Analytics & Testing',
        completed: false,
        items: [
          createItem('SQL aggregation queries', 'topic'),
          createItem('ACID transactions', 'topic'),
          createItem('Jest + Supertest', 'topic'),
          createItem('Node.js Jest tutorial', 'youtube', 'Node.js Jest tutorial'),
          createItem('Node.js Supertest tutorial', 'youtube', 'Node.js Supertest tutorial'),
        ],
      },
      {
        id: 'month-5-week-4',
        weekNumber: 4,
        title: 'Docker & Containerization',
        completed: false,
        items: [
          createItem('Dockerfile', 'topic'),
          createItem('docker-compose', 'topic'),
          createItem('Containerizing Node.js + PostgreSQL + Redis', 'project'),
          createItem('Docker Node.js tutorial', 'youtube', 'Docker Node.js tutorial'),
          createItem('docker-compose Node.js tutorial', 'youtube', 'docker-compose Node.js tutorial'),
        ],
      },
    ],
  },
  {
    id: 'month-6',
    monthNumber: 6,
    title: 'DevOps & Job Hunt',
    goal: 'Learn DevOps basics, polish portfolio, and start applying.',
    completed: false,
    weeks: [
      {
        id: 'month-6-week-1',
        weekNumber: 1,
        title: 'DevOps Basics',
        completed: false,
        items: [
          createItem('NGINX reverse proxy', 'topic'),
          createItem('PM2 monitoring', 'topic'),
          createItem('NGINX reverse proxy tutorial', 'youtube', 'NGINX reverse proxy tutorial'),
          createItem('PM2 Node.js tutorial', 'youtube', 'PM2 Node.js tutorial'),
        ],
      },
      {
        id: 'month-6-week-2',
        weekNumber: 2,
        title: 'Resume & GitHub Polish',
        completed: false,
        items: [
          createItem('Update GitHub with screenshots', 'project'),
          createItem('README.md with deployment instructions', 'project'),
          createItem('Highlight: Docker, Prisma, Next.js, PostgreSQL', 'topic'),
          createItem('How to create a developer portfolio on GitHub', 'youtube', 'How to create a developer portfolio on GitHub'),
          createItem('GitHub README tutorial', 'youtube', 'GitHub README tutorial'),
        ],
      },
      {
        id: 'month-6-week-3',
        weekNumber: 3,
        title: 'Mock Interviews',
        completed: false,
        items: [
          createItem('Practice: Event Loop', 'practice'),
          createItem('Practice: Indexing', 'practice'),
          createItem('Practice: JWT flow', 'practice'),
          createItem('Practice: REST API concepts', 'practice'),
          createItem('Practice: System design diagrams', 'practice'),
          createItem('Node.js interview questions', 'youtube', 'Node.js interview questions'),
          createItem('Backend system design for beginners', 'youtube', 'Backend system design for beginners'),
        ],
      },
      {
        id: 'month-6-week-4',
        weekNumber: 4,
        title: 'Applications',
        completed: false,
        items: [
          createItem('Apply to 20+ roles on LinkedIn', 'project'),
          createItem('Apply on BdJobs', 'project'),
          createItem('Apply on Indeed', 'project'),
          createItem('Apply on company portals', 'project'),
          createItem('How to apply for software jobs in Bangladesh 2026', 'youtube', 'How to apply for software jobs in Bangladesh 2026'),
        ],
      },
    ],
  },
];

