import { Month, LearningItem, Day, Week } from './roadmapTypes';

// Helper to create learning items
function createItem(
  title: string,
  type: LearningItem['type'],
  searchKeyword?: string,
  count?: number
): LearningItem {
  return {
    id: `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    title,
    type,
    completed: false,
    searchKeyword,
    count,
    currentCount: 0,
  };
}

// Helper to create a day
function createDay(dayNumber: number, title: string, items: LearningItem[]): Day {
  return {
    id: `day-${dayNumber}`,
    dayNumber,
    title,
    items,
    completed: false,
  };
}

// Helper to create a week
function createWeek(weekNumber: number, title: string, days: Day[]): Week {
  return {
    id: `week-${weekNumber}`,
    weekNumber,
    title,
    days,
    completed: false,
  };
}

export const roadmapData: Month[] = [
  {
    id: 'month-1',
    monthNumber: 1,
    title: 'The Engineer\'s Foundation',
    goal: 'Master Web Architecture, Git, JavaScript Runtime, and Logic.',
    completed: false,
    weeks: [
      createWeek(1, 'Web Architecture, Git & JS Syntax', [
        createDay(1, 'Web & Git Setup', [
          createItem('HTTP vs HTTPS', 'topic'),
          createItem('DNS Resolution', 'topic'),
          createItem('Request/Response Cycle', 'topic'),
          createItem('Git Init/Commit/Push', 'topic'),
          createItem('how the web works dns http tcp ip', 'search', 'how the web works dns http tcp ip'),
          createItem('gitflow workflow tutorial 2026', 'search', 'gitflow workflow tutorial 2026'),
        ]),
        createDay(2, 'JS Variables & Loops', [
          createItem('let vs const vs var', 'topic'),
          createItem('Data Types', 'topic'),
          createItem('for loops vs map/forEach', 'topic'),
          createItem('javascript variables let const var explained', 'search', 'javascript variables let const var explained'),
          createItem('javascript loops vs map', 'search', 'javascript loops vs map'),
        ]),
        createDay(3, 'Functions & Objects', [
          createItem('Function Declarations vs Expressions', 'topic'),
          createItem('Object Destructuring', 'topic'),
          createItem('Spread Operator', 'topic'),
          createItem('javascript object destructuring tutorial', 'search', 'javascript object destructuring tutorial'),
          createItem('javascript spread operator uses', 'search', 'javascript spread operator uses'),
        ]),
        createDay(4, 'ES6+ Modern JS', [
          createItem('Arrow Functions', 'topic'),
          createItem('Template Literals', 'topic'),
          createItem('Modules (Import/Export)', 'topic'),
          createItem('javascript es6 features crash course', 'search', 'javascript es6 features crash course'),
          createItem('javascript modules import export', 'search', 'javascript modules import export'),
        ]),
        createDay(5, 'Async JavaScript', [
          createItem('Callbacks', 'topic'),
          createItem('Promises', 'topic'),
          createItem('Async/Await syntax', 'topic'),
          createItem('try/catch blocks', 'topic'),
          createItem('javascript async await fetch api tutorial', 'search', 'javascript async await fetch api tutorial'),
          createItem('javascript promises explained', 'search', 'javascript promises explained'),
        ]),
        createDay(6, 'Error Handling Patterns', [
          createItem('Custom Error Classes', 'topic'),
          createItem('Error Propagation', 'topic'),
          createItem('Graceful Degradation', 'topic'),
          createItem('Error Boundaries', 'topic'),
          createItem('javascript custom error classes', 'search', 'javascript custom error classes'),
          createItem('error handling best practices javascript 2026', 'search', 'error handling best practices javascript 2026'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(2, 'JavaScript Runtime (The Engine)', [
        createDay(1, 'V8 Engine & Call Stack', [
          createItem('Single Threaded nature', 'topic'),
          createItem('Call Stack', 'topic'),
          createItem('Memory Heap', 'topic'),
          createItem('javascript call stack visualizer', 'search', 'javascript call stack visualizer'),
          createItem('how v8 engine works', 'search', 'how v8 engine works'),
        ]),
        createDay(2, 'Event Loop & Queues', [
          createItem('Event Loop mechanics', 'topic'),
          createItem('Macro-tasks (setTimeout) vs Micro-tasks (Promises)', 'topic'),
          createItem('nodejs event loop visualization 2026', 'search', 'nodejs event loop visualization 2026'),
        ]),
        createDay(3, 'Blocking vs Non-Blocking', [
          createItem('I/O operations', 'topic'),
          createItem('Blocking the main thread', 'topic'),
          createItem('Concurrency', 'topic'),
          createItem('blocking vs non-blocking nodejs explained', 'search', 'blocking vs non-blocking nodejs explained'),
        ]),
        createDay(4, 'Node.js Modules', [
          createItem('CommonJS (require) vs ES Modules (import)', 'topic'),
          createItem('module.exports', 'topic'),
          createItem('nodejs require vs import explained', 'search', 'nodejs require vs import explained'),
        ]),
        createDay(5, 'HTTP & Status Codes', [
          createItem('Headers', 'topic'),
          createItem('Body', 'topic'),
          createItem('Status Codes (200, 201, 400, 401, 403, 404, 500)', 'topic'),
          createItem('http status codes explained', 'search', 'http status codes explained'),
          createItem('http headers crash course', 'search', 'http headers crash course'),
        ]),
        createDay(6, 'Deep Logic Practice', [
          createItem('Sliding Window pattern', 'practice'),
          createItem('Two Pointer technique', 'practice'),
          createItem('leetcode sliding window pattern javascript', 'search', 'leetcode sliding window pattern javascript'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(3, 'TypeScript (Strict Mode)', [
        createDay(1, 'TS Setup & Basic Types', [
          createItem('tsconfig.json setup', 'topic'),
          createItem('String/Number/Boolean', 'topic'),
          createItem('Arrays', 'topic'),
          createItem('any (and why to avoid it)', 'topic'),
          createItem('setup nodejs typescript nodemon', 'search', 'setup nodejs typescript nodemon'),
          createItem('typescript basic types', 'search', 'typescript basic types'),
        ]),
        createDay(2, 'Interfaces & Types', [
          createItem('Interface vs Type Alias', 'topic'),
          createItem('Optional Properties', 'topic'),
          createItem('Readonly', 'topic'),
          createItem('typescript interface vs type explained', 'search', 'typescript interface vs type explained'),
        ]),
        createDay(3, 'Generics & Utility Types', [
          createItem('Generic Functions <T>', 'topic'),
          createItem('Partial', 'topic'),
          createItem('Pick', 'topic'),
          createItem('Omit', 'topic'),
          createItem('typescript generics explained', 'search', 'typescript generics explained'),
          createItem('typescript utility types tutorial', 'search', 'typescript utility types tutorial'),
        ]),
        createDay(4, 'OOP in TypeScript', [
          createItem('Classes', 'topic'),
          createItem('Access Modifiers (public/private/protected)', 'topic'),
          createItem('Inheritance', 'topic'),
          createItem('object oriented programming typescript', 'search', 'object oriented programming typescript'),
        ]),
        createDay(5, 'Promise & Async TS', [
          createItem('Typing Promises', 'topic'),
          createItem('Async function return types', 'topic'),
          createItem('typescript async await types', 'search', 'typescript async await types'),
        ]),
        createDay(6, 'Mini Project (CLI)', [
          createItem('Building a small Command Line Interface tool with TS', 'project'),
          createItem('build cli tool nodejs typescript', 'search', 'build cli tool nodejs typescript'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(4, 'DSA for Backend', [
        createDay(1, 'Hash Maps', [
          createItem('Key-Value pairs', 'topic'),
          createItem('Frequency Counters', 'topic'),
          createItem('Map vs Object', 'topic'),
          createItem('hash map data structure javascript', 'search', 'hash map data structure javascript'),
        ]),
        createDay(2, 'Stacks & Queues', [
          createItem('LIFO vs FIFO', 'topic'),
          createItem('implementing them in JS', 'topic'),
          createItem('stack vs queue data structure javascript', 'search', 'stack vs queue data structure javascript'),
        ]),
        createDay(3, 'Recursion', [
          createItem('Base case', 'topic'),
          createItem('recursive step', 'topic'),
          createItem('factorial/fibonacci examples', 'topic'),
          createItem('recursion javascript tutorial', 'search', 'recursion javascript tutorial'),
        ]),
        createDay(4, 'Time Complexity', [
          createItem('Big O Notation', 'topic'),
          createItem('O(1) vs O(n) vs O(n^2)', 'topic'),
          createItem('big o notation explained javascript', 'search', 'big o notation explained javascript'),
        ]),
        createDay(5, 'Git Advanced', [
          createItem('Git Merge vs Rebase', 'topic'),
          createItem('Resolving Conflicts', 'topic'),
          createItem('Cherry-pick', 'topic'),
          createItem('Git Hooks', 'topic'),
          createItem('Husky Setup', 'topic'),
          createItem('git merge vs rebase explained', 'search', 'git merge vs rebase explained'),
          createItem('git hooks husky tutorial', 'search', 'git hooks husky tutorial'),
          createItem('git conflict resolution', 'search', 'git conflict resolution'),
        ]),
        createDay(6, 'Logic Practice (Arrays)', [
          createItem('Sorting', 'practice'),
          createItem('Searching', 'practice'),
          createItem('Duplicates', 'practice'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
    ],
  },
  {
    id: 'month-2',
    monthNumber: 2,
    title: 'Backend Basics',
    goal: 'Build APIs with Node.js, Express, MongoDB, and integrate File Uploads.',
    completed: false,
    weeks: [
      createWeek(1, 'Node.js, Express & Debugging', [
        createDay(1, 'File System & Streams', [
          createItem('Reading/Writing files (fs module)', 'topic'),
          createItem('path manipulation', 'topic'),
          createItem('Streams for Large Files', 'topic'),
          createItem('Buffer vs Stream', 'topic'),
          createItem('nodejs fs module tutorial', 'search', 'nodejs fs module tutorial'),
          createItem('nodejs streams explained', 'search', 'nodejs streams explained'),
          createItem('readable writable streams nodejs', 'search', 'readable writable streams nodejs'),
        ]),
        createDay(2, 'Express Server Setup', [
          createItem('Creating a server', 'topic'),
          createItem('Request/Response objects', 'topic'),
          createItem('basic routing', 'topic'),
          createItem('express js crash course', 'search', 'express js crash course'),
        ]),
        createDay(3, 'Middleware', [
          createItem('Application-level vs Router-level middleware', 'topic'),
          createItem('next()', 'topic'),
          createItem('express middleware explained', 'search', 'express middleware explained'),
        ]),
        createDay(4, 'Input Validation & Sanitization', [
          createItem('Zod Validation Library', 'topic'),
          createItem('Express-validator', 'topic'),
          createItem('XSS Prevention', 'topic'),
          createItem('SQL Injection Prevention', 'topic'),
          createItem('Input Sanitization', 'topic'),
          createItem('zod express validation tutorial', 'search', 'zod express validation tutorial'),
          createItem('prevent xss attacks nodejs', 'search', 'prevent xss attacks nodejs'),
          createItem('input sanitization nodejs', 'search', 'input sanitization nodejs'),
        ]),
        createDay(5, 'Unit Testing Basics', [
          createItem('Jest/Vitest Setup', 'topic'),
          createItem('Writing Test Cases', 'topic'),
          createItem('Assertions (expect)', 'topic'),
          createItem('Mocking Functions', 'topic'),
          createItem('Test Coverage', 'topic'),
          createItem('jest nodejs tutorial', 'search', 'jest nodejs tutorial'),
          createItem('vitest vs jest 2026', 'search', 'vitest vs jest 2026'),
          createItem('nodejs unit testing best practices', 'search', 'nodejs unit testing best practices'),
        ]),
        createDay(6, 'Testing Express Routes', [
          createItem('Supertest Library', 'topic'),
          createItem('Testing GET/POST/PUT/DELETE', 'topic'),
          createItem('Testing Middleware', 'topic'),
          createItem('Status Code Assertions', 'topic'),
          createItem('supertest express api testing', 'search', 'supertest express api testing'),
          createItem('testing express middleware jest', 'search', 'testing express middleware jest'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(2, 'MongoDB & Mongoose', [
        createDay(1, 'MongoDB Setup & Design Patterns', [
          createItem('MongoDB Compass & Atlas', 'topic'),
          createItem('Connection strings', 'topic'),
          createItem('Collections', 'topic'),
          createItem('Document Design Patterns (Embedding vs Referencing)', 'topic'),
          createItem('mongodb atlas tutorial', 'search', 'mongodb atlas tutorial'),
          createItem('mongodb schema design patterns', 'search', 'mongodb schema design patterns'),
          createItem('embedding vs referencing mongodb', 'search', 'embedding vs referencing mongodb'),
        ]),
        createDay(2, 'Mongoose Schemas', [
          createItem('Defining Models', 'topic'),
          createItem('Data Types', 'topic'),
          createItem('Validation', 'topic'),
          createItem('Required fields', 'topic'),
          createItem('mongoose schema validation', 'search', 'mongoose schema validation'),
        ]),
        createDay(3, 'Advanced Queries & Indexing', [
          createItem('Filtering ($gt, $lt)', 'topic'),
          createItem('Logic ($or, $and)', 'topic'),
          createItem('Sorting', 'topic'),
          createItem('Limiting', 'topic'),
          createItem('Creating Indexes', 'topic'),
          createItem('Index Types (Single, Compound, Text)', 'topic'),
          createItem('mongodb advanced queries tutorial', 'search', 'mongodb advanced queries tutorial'),
          createItem('mongodb indexing best practices', 'search', 'mongodb indexing best practices'),
          createItem('mongodb compound indexes', 'search', 'mongodb compound indexes'),
        ]),
        createDay(4, 'Aggregation Framework', [
          createItem('Pipelines', 'topic'),
          createItem('$match', 'topic'),
          createItem('$group', 'topic'),
          createItem('$lookup (Joins)', 'topic'),
          createItem('mongodb aggregation pipeline tutorial', 'search', 'mongodb aggregation pipeline tutorial'),
        ]),
        createDay(5, 'Testing with MongoDB', [
          createItem('mongodb-memory-server Setup', 'topic'),
          createItem('Test Database Configuration', 'topic'),
          createItem('beforeEach/afterEach Cleanup', 'topic'),
          createItem('Seeding Test Data', 'topic'),
          createItem('mongodb memory server jest', 'search', 'mongodb memory server jest'),
          createItem('testing mongodb nodejs', 'search', 'testing mongodb nodejs'),
          createItem('jest setup teardown mongodb', 'search', 'jest setup teardown mongodb'),
        ]),
        createDay(6, 'Project Integration', [
          createItem('Connecting Express API to MongoDB', 'project'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(3, 'Auth & Security (JWT)', [
        createDay(1, 'Hashing', [
          createItem('Bcrypt', 'topic'),
          createItem('Salting', 'topic'),
          createItem('Hash comparison', 'topic'),
          createItem('bcrypt password hashing nodejs', 'search', 'bcrypt password hashing nodejs'),
        ]),
        createDay(2, 'JWT Basics', [
          createItem('Signing tokens', 'topic'),
          createItem('verify signature', 'topic'),
          createItem('decoding payloads', 'topic'),
          createItem('jwt authentication nodejs explained', 'search', 'jwt authentication nodejs explained'),
        ]),
        createDay(3, 'Auth Middleware & Testing', [
          createItem('Protecting routes', 'topic'),
          createItem('extracting tokens from Headers', 'topic'),
          createItem('Testing Auth Routes', 'topic'),
          createItem('Mocking JWT', 'topic'),
          createItem('express js route protection jwt', 'search', 'express js route protection jwt'),
          createItem('testing jwt authentication jest', 'search', 'testing jwt authentication jest'),
          createItem('mocking jwt token tests', 'search', 'mocking jwt token tests'),
        ]),
        createDay(4, 'Refresh Tokens', [
          createItem('Short-lived access tokens vs Long-lived refresh tokens', 'topic'),
          createItem('refresh token rotation nodejs', 'search', 'refresh token rotation nodejs'),
        ]),
        createDay(5, 'RBAC (Roles)', [
          createItem('Admin vs User permissions', 'topic'),
          createItem('checking roles in middleware', 'topic'),
          createItem('rbac nodejs express tutorial', 'search', 'rbac nodejs express tutorial'),
        ]),
        createDay(6, 'Rate Limiting & DDoS Protection', [
          createItem('express-rate-limit Library', 'topic'),
          createItem('Window Types (Fixed vs Sliding)', 'topic'),
          createItem('IP-based Limiting', 'topic'),
          createItem('Preventing Brute Force', 'topic'),
          createItem('express rate limiting tutorial', 'search', 'express rate limiting tutorial'),
          createItem('prevent brute force attacks nodejs', 'search', 'prevent brute force attacks nodejs'),
          createItem('sliding window rate limit', 'search', 'sliding window rate limit'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(4, 'API Design & Documentation', [
        createDay(1, 'RESTful API Best Practices', [
          createItem('Resource Naming Conventions', 'topic'),
          createItem('HTTP Verbs (GET/POST/PUT/PATCH/DELETE)', 'topic'),
          createItem('Idempotency', 'topic'),
          createItem('API Versioning (URL vs Header)', 'topic'),
          createItem('rest api design best practices 2026', 'search', 'rest api design best practices 2026'),
          createItem('api versioning strategies', 'search', 'api versioning strategies'),
          createItem('http idempotency explained', 'search', 'http idempotency explained'),
        ]),
        createDay(2, 'Pagination & Filtering', [
          createItem('Limit/Offset Pagination', 'topic'),
          createItem('Cursor-based Pagination', 'topic'),
          createItem('Query Parameters', 'topic'),
          createItem('Sorting', 'topic'),
          createItem('Field Selection', 'topic'),
          createItem('api pagination best practices', 'search', 'api pagination best practices'),
          createItem('cursor based pagination mongodb', 'search', 'cursor based pagination mongodb'),
          createItem('rest api filtering sorting', 'search', 'rest api filtering sorting'),
        ]),
        createDay(3, 'API Documentation - Swagger', [
          createItem('OpenAPI Specification', 'topic'),
          createItem('Swagger UI Setup', 'topic'),
          createItem('JSDoc Annotations', 'topic'),
          createItem('Request/Response Examples', 'topic'),
          createItem('swagger nodejs express tutorial', 'search', 'swagger nodejs express tutorial'),
          createItem('openapi 3.0 specification', 'search', 'openapi 3.0 specification'),
          createItem('swagger jsdoc annotations', 'search', 'swagger jsdoc annotations'),
        ]),
        createDay(4, 'Standardized Error Responses', [
          createItem('Global Error Handler Middleware', 'topic'),
          createItem('Error Response Format (RFC 7807)', 'topic'),
          createItem('HTTP Status Code Selection', 'topic'),
          createItem('Winston/Pino Logging', 'topic'),
          createItem('express global error handler', 'search', 'express global error handler'),
          createItem('nodejs error logging winston', 'search', 'nodejs error logging winston'),
          createItem('rfc 7807 problem details', 'search', 'rfc 7807 problem details'),
        ]),
        createDay(5, 'Integration Testing', [
          createItem('End-to-End API Tests', 'topic'),
          createItem('Test Suites', 'topic'),
          createItem('Test Coverage Reports (Istanbul/c8)', 'topic'),
          createItem('CI Integration', 'topic'),
          createItem('integration testing nodejs', 'search', 'integration testing nodejs'),
          createItem('jest coverage report', 'search', 'jest coverage report'),
          createItem('e2e api testing supertest', 'search', 'e2e api testing supertest'),
        ]),
        createDay(6, 'Tested Blog API Project', [
          createItem('Build Complete CRUD API with Auth', 'project'),
          createItem('Full Test Coverage (Unit + Integration)', 'project'),
          createItem('Swagger Docs', 'project'),
          createItem('nodejs blog api with tests', 'search', 'nodejs blog api with tests'),
          createItem('express crud api testing example', 'search', 'express crud api testing example'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
    ],
  },
  {
    id: 'month-3',
    monthNumber: 3,
    title: 'RDBMS & Architecture',
    goal: 'Master PostgreSQL, Prisma, and Next.js Backend.',
    completed: false,
    weeks: [
      createWeek(1, 'PostgreSQL & SQL', [
        createDay(1, 'Relational Design', [
          createItem('Tables', 'topic'),
          createItem('Rows', 'topic'),
          createItem('Columns', 'topic'),
          createItem('Primary Keys', 'topic'),
          createItem('Foreign Keys', 'topic'),
          createItem('er diagram tutorial for beginners', 'search', 'er diagram tutorial for beginners'),
        ]),
        createDay(2, 'Normalization', [
          createItem('1NF', 'topic'),
          createItem('2NF', 'topic'),
          createItem('3NF', 'topic'),
          createItem('reducing redundancy', 'topic'),
          createItem('database normalization 1nf 2nf 3nf', 'search', 'database normalization 1nf 2nf 3nf'),
        ]),
        createDay(3, 'Basic SQL & Indexing', [
          createItem('SELECT statements', 'topic'),
          createItem('INSERT statements', 'topic'),
          createItem('UPDATE statements', 'topic'),
          createItem('DELETE statements', 'topic'),
          createItem('Creating Indexes', 'topic'),
          createItem('B-tree Indexes', 'topic'),
          createItem('When to Index', 'topic'),
          createItem('postgresql sql queries tutorial', 'search', 'postgresql sql queries tutorial'),
          createItem('postgresql indexing explained', 'search', 'postgresql indexing explained'),
          createItem('database index performance', 'search', 'database index performance'),
        ]),
        createDay(4, 'Joins', [
          createItem('INNER JOIN', 'topic'),
          createItem('LEFT JOIN', 'topic'),
          createItem('RIGHT JOIN', 'topic'),
          createItem('postgresql joins visual explanation', 'search', 'postgresql joins visual explanation'),
        ]),
        createDay(5, 'Transactions & Connection Pooling', [
          createItem('ACID properties', 'topic'),
          createItem('BEGIN', 'topic'),
          createItem('COMMIT', 'topic'),
          createItem('ROLLBACK', 'topic'),
          createItem('Connection Pooling', 'topic'),
          createItem('Pool Size Configuration', 'topic'),
          createItem('acid transactions sql explained', 'search', 'acid transactions sql explained'),
          createItem('postgresql connection pooling', 'search', 'postgresql connection pooling'),
          createItem('pg pool configuration', 'search', 'pg pool configuration'),
        ]),
        createDay(6, 'DB Setup', [
          createItem('Setting up Postgres locally or on Neon/Supabase', 'project'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(2, 'Prisma ORM', [
        createDay(1, 'Prisma Model', [
          createItem('schema.prisma syntax', 'topic'),
          createItem('defining models', 'topic'),
          createItem('prisma orm crash course', 'search', 'prisma orm crash course'),
        ]),
        createDay(2, 'Migrations', [
          createItem('Creating migrations', 'topic'),
          createItem('applying to DB', 'topic'),
          createItem('version control', 'topic'),
          createItem('prisma migrate explained', 'search', 'prisma migrate explained'),
        ]),
        createDay(3, 'Relations', [
          createItem('One-to-One', 'topic'),
          createItem('One-to-Many', 'topic'),
          createItem('Many-to-Many syntax', 'topic'),
          createItem('prisma schema relations', 'search', 'prisma schema relations'),
        ]),
        createDay(4, 'CRUD with Prisma & Optimization', [
          createItem('findMany', 'topic'),
          createItem('create', 'topic'),
          createItem('update', 'topic'),
          createItem('delete', 'topic'),
          createItem('Query Optimization', 'topic'),
          createItem('Select Fields', 'topic'),
          createItem('Includes', 'topic'),
          createItem('prisma client crud operations', 'search', 'prisma client crud operations'),
          createItem('prisma query optimization', 'search', 'prisma query optimization'),
          createItem('prisma select include', 'search', 'prisma select include'),
        ]),
        createDay(5, 'Filtering, Sorting & Transactions', [
          createItem('Where clauses', 'topic'),
          createItem('Ordering', 'topic'),
          createItem('Pagination', 'topic'),
          createItem('Prisma Transactions', 'topic'),
          createItem('Interactive Transactions', 'topic'),
          createItem('prisma filtering and sorting', 'search', 'prisma filtering and sorting'),
          createItem('prisma transactions tutorial', 'search', 'prisma transactions tutorial'),
          createItem('prisma interactive transactions', 'search', 'prisma interactive transactions'),
        ]),
        createDay(6, 'Project Practice', [
          createItem('Building a University Schema (Students/Courses)', 'project'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(3, 'Next.js 15 Backend', [
        createDay(1, 'App Router', [
          createItem('Folder structure', 'topic'),
          createItem('page.tsx', 'topic'),
          createItem('layout.tsx', 'topic'),
          createItem('nextjs 15 app router crash course', 'search', 'nextjs 15 app router crash course'),
        ]),
        createDay(2, 'Server Components', [
          createItem('Fetching data on the server', 'topic'),
          createItem('async components', 'topic'),
          createItem('react server components explained', 'search', 'react server components explained'),
        ]),
        createDay(3, 'Server Actions', [
          createItem('Form submissions without API routes', 'topic'),
          createItem('use server', 'topic'),
          createItem('nextjs server actions tutorial', 'search', 'nextjs server actions tutorial'),
        ]),
        createDay(4, 'Route Handlers', [
          createItem('Creating route.ts (GET/POST) for external APIs', 'topic'),
          createItem('nextjs api routes tutorial', 'search', 'nextjs api routes tutorial'),
        ]),
        createDay(5, 'Data Fetching & Rendering Strategies', [
          createItem('Caching', 'topic'),
          createItem('Revalidating data', 'topic'),
          createItem('fetch API extensions', 'topic'),
          createItem('ISR (Incremental Static Regeneration)', 'topic'),
          createItem('SSG vs SSR', 'topic'),
          createItem('nextjs data fetching server side', 'search', 'nextjs data fetching server side'),
          createItem('nextjs isr explained', 'search', 'nextjs isr explained'),
          createItem('nextjs ssg vs ssr', 'search', 'nextjs ssg vs ssr'),
        ]),
        createDay(6, 'Blog Project', [
          createItem('Building a Blog with Next.js + Prisma', 'project'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(4, 'Architecture & Quality', [
        createDay(1, 'Service Pattern', [
          createItem('Separating Business Logic from Controllers', 'topic'),
          createItem('nodejs service controller pattern', 'search', 'nodejs service controller pattern'),
        ]),
        createDay(2, 'Zod Validation & Environment Variables', [
          createItem('Schema validation for inputs', 'topic'),
          createItem('Environment Variables Validation', 'topic'),
          createItem('.env.local vs .env.production', 'topic'),
          createItem('Type-safe Env', 'topic'),
          createItem('zod validation tutorial', 'search', 'zod validation tutorial'),
          createItem('nextjs environment variables', 'search', 'nextjs environment variables'),
          createItem('zod environment validation', 'search', 'zod environment validation'),
        ]),
        createDay(3, 'Error Handling & Logging', [
          createItem('error.tsx in Next.js', 'topic'),
          createItem('Custom Error classes', 'topic'),
          createItem('Winston/Pino Logging', 'topic'),
          createItem('Log Levels', 'topic'),
          createItem('Structured Logging', 'topic'),
          createItem('nextjs error handling best practices', 'search', 'nextjs error handling best practices'),
          createItem('winston logger nodejs', 'search', 'winston logger nodejs'),
          createItem('pino logging tutorial', 'search', 'pino logging tutorial'),
        ]),
        createDay(4, 'Linting & Pre-commit Hooks', [
          createItem('ESLint', 'topic'),
          createItem('Prettier setup', 'topic'),
          createItem('Husky Pre-commit Hooks', 'topic'),
          createItem('lint-staged', 'topic'),
          createItem('Commit Message Linting', 'topic'),
          createItem('eslint prettier setup nextjs', 'search', 'eslint prettier setup nextjs'),
          createItem('husky pre commit hooks', 'search', 'husky pre commit hooks'),
          createItem('lint staged tutorial', 'search', 'lint staged tutorial'),
        ]),
        createDay(5, 'Refactoring', [
          createItem('Cleaning up code', 'topic'),
          createItem('applying patterns', 'topic'),
        ]),
        createDay(6, 'Refactoring', [
          createItem('Cleaning up code', 'topic'),
          createItem('applying patterns', 'topic'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
    ],
  },
  {
    id: 'month-4',
    monthNumber: 4,
    title: 'Capstone 1 - DeshDoor',
    goal: 'Build a Service Marketplace (Next.js, Postgres, Prisma, Cloudinary).',
    completed: false,
    weeks: [
      createWeek(1, 'Auth & Setup', [
        createDay(1, 'Next.js Setup', [
          createItem('Next.js Setup', 'topic'),
          createItem('ShadcnUI', 'topic'),
          createItem('NextAuth v5 Configuration (Providers, Callbacks)', 'topic'),
          createItem('next-auth v5 role based access control', 'search', 'next-auth v5 role based access control'),
        ]),
        createDay(2, 'Next.js Setup', [
          createItem('Next.js Setup', 'topic'),
          createItem('ShadcnUI', 'topic'),
          createItem('NextAuth v5 Configuration (Providers, Callbacks)', 'topic'),
        ]),
        createDay(3, 'Next.js Setup', [
          createItem('Next.js Setup', 'topic'),
          createItem('ShadcnUI', 'topic'),
          createItem('NextAuth v5 Configuration (Providers, Callbacks)', 'topic'),
        ]),
        createDay(4, 'Next.js Setup', [
          createItem('Next.js Setup', 'topic'),
          createItem('ShadcnUI', 'topic'),
          createItem('NextAuth v5 Configuration (Providers, Callbacks)', 'topic'),
        ]),
        createDay(5, 'Next.js Setup', [
          createItem('Next.js Setup', 'topic'),
          createItem('ShadcnUI', 'topic'),
          createItem('NextAuth v5 Configuration (Providers, Callbacks)', 'topic'),
        ]),
        createDay(6, 'Next.js Setup', [
          createItem('Next.js Setup', 'topic'),
          createItem('ShadcnUI', 'topic'),
          createItem('NextAuth v5 Configuration (Providers, Callbacks)', 'topic'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(2, 'Services & Images', [
        createDay(1, 'DB Schema & Images', [
          createItem('DB Schema for Services', 'topic'),
          createItem('Image Upload to Cloudinary', 'topic'),
          createItem('nextjs cloudinary upload widget tutorial', 'search', 'nextjs cloudinary upload widget tutorial'),
        ]),
        createDay(2, 'Services & Image Optimization', [
          createItem('DB Schema for Services', 'topic'),
          createItem('Image Upload to Cloudinary', 'topic'),
          createItem('Image Optimization', 'topic'),
          createItem('Next.js Image Component', 'topic'),
          createItem('Cloudinary Transformations', 'topic'),
          createItem('nextjs cloudinary upload widget tutorial', 'search', 'nextjs cloudinary upload widget tutorial'),
          createItem('nextjs image optimization', 'search', 'nextjs image optimization'),
          createItem('cloudinary transformations', 'search', 'cloudinary transformations'),
        ]),
        createDay(3, 'DB Schema & Images', [
          createItem('DB Schema for Services', 'topic'),
          createItem('Image Upload to Cloudinary', 'topic'),
        ]),
        createDay(4, 'DB Schema & Images', [
          createItem('DB Schema for Services', 'topic'),
          createItem('Image Upload to Cloudinary', 'topic'),
        ]),
        createDay(5, 'DB Schema & Images', [
          createItem('DB Schema for Services', 'topic'),
          createItem('Image Upload to Cloudinary', 'topic'),
        ]),
        createDay(6, 'DB Schema & Images', [
          createItem('DB Schema for Services', 'topic'),
          createItem('Image Upload to Cloudinary', 'topic'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(3, 'Booking Logic', [
        createDay(1, 'Booking System', [
          createItem('Relational Schema (User-Booking-Service)', 'topic'),
          createItem('Transactions', 'topic'),
          createItem('Vendor Dashboard', 'topic'),
          createItem('prisma transaction booking system', 'search', 'prisma transaction booking system'),
        ]),
        createDay(2, 'Booking System', [
          createItem('Relational Schema (User-Booking-Service)', 'topic'),
          createItem('Transactions', 'topic'),
          createItem('Vendor Dashboard', 'topic'),
        ]),
        createDay(3, 'Booking Logic & Testing', [
          createItem('Relational Schema (User-Booking-Service)', 'topic'),
          createItem('Transactions', 'topic'),
          createItem('Vendor Dashboard', 'topic'),
          createItem('Testing Booking Logic', 'topic'),
          createItem('prisma transaction booking system', 'search', 'prisma transaction booking system'),
          createItem('testing booking system nodejs', 'search', 'testing booking system nodejs'),
        ]),
        createDay(4, 'Booking System', [
          createItem('Relational Schema (User-Booking-Service)', 'topic'),
          createItem('Transactions', 'topic'),
          createItem('Vendor Dashboard', 'topic'),
        ]),
        createDay(5, 'Booking System', [
          createItem('Relational Schema (User-Booking-Service)', 'topic'),
          createItem('Transactions', 'topic'),
          createItem('Vendor Dashboard', 'topic'),
        ]),
        createDay(6, 'Booking System', [
          createItem('Relational Schema (User-Booking-Service)', 'topic'),
          createItem('Transactions', 'topic'),
          createItem('Vendor Dashboard', 'topic'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(4, 'Deploy & Docs', [
        createDay(1, 'Deploy & CI/CD Pipeline', [
          createItem('Deploying to Vercel + Neon', 'project'),
          createItem('GitHub Actions CI/CD', 'topic'),
          createItem('Automated Testing', 'topic'),
          createItem('Build Checks', 'topic'),
          createItem('Deploy Previews', 'topic'),
          createItem('deploy nextjs prisma vercel', 'search', 'deploy nextjs prisma vercel'),
          createItem('github actions nextjs deployment', 'search', 'github actions nextjs deployment'),
          createItem('ci cd pipeline nodejs', 'search', 'ci cd pipeline nodejs'),
        ]),
        createDay(2, 'Monitoring & Error Tracking', [
          createItem('Sentry Setup', 'topic'),
          createItem('Error Reporting', 'topic'),
          createItem('Source Maps', 'topic'),
          createItem('Performance Monitoring', 'topic'),
          createItem('User Feedback Integration', 'topic'),
          createItem('sentry nextjs integration', 'search', 'sentry nextjs integration'),
          createItem('error tracking nodejs', 'search', 'error tracking nodejs'),
          createItem('sentry performance monitoring', 'search', 'sentry performance monitoring'),
        ]),
        createDay(3, 'Deploy & CI/CD Pipeline', [
          createItem('Deploying to Vercel + Neon', 'project'),
          createItem('GitHub Actions CI/CD', 'topic'),
          createItem('Automated Testing', 'topic'),
          createItem('Build Checks', 'topic'),
          createItem('Deploy Previews', 'topic'),
        ]),
        createDay(4, 'Monitoring & Error Tracking', [
          createItem('Sentry Setup', 'topic'),
          createItem('Error Reporting', 'topic'),
          createItem('Source Maps', 'topic'),
          createItem('Performance Monitoring', 'topic'),
          createItem('User Feedback Integration', 'topic'),
        ]),
        createDay(5, 'Documentation & Final Polish', [
          createItem('Writing README.md', 'project'),
          createItem('API Documentation', 'project'),
          createItem('Code Review & Refactoring', 'project'),
        ]),
        createDay(6, 'Catch up / Buffer', []),
        createDay(7, 'Review & Rest', []),
      ]),
    ],
  },
  {
    id: 'month-5',
    monthNumber: 5,
    title: 'Capstone 2 - RideShare',
    goal: 'Microservices, Real-time, Redis',
    completed: false,
    weeks: [
      createWeek(1, 'Redis & Caching', [
        createDay(1, 'Redis Setup', [
          createItem('Redis Setup', 'topic'),
          createItem('SET/GET', 'topic'),
          createItem('Expiration', 'topic'),
          createItem('Caching API responses', 'topic'),
          createItem('redis caching strategy nodejs', 'search', 'redis caching strategy nodejs'),
        ]),
        createDay(2, 'Redis Setup', [
          createItem('Redis Setup', 'topic'),
          createItem('SET/GET', 'topic'),
          createItem('Expiration', 'topic'),
          createItem('Caching API responses', 'topic'),
        ]),
        createDay(3, 'Redis Setup', [
          createItem('Redis Setup', 'topic'),
          createItem('SET/GET', 'topic'),
          createItem('Expiration', 'topic'),
          createItem('Caching API responses', 'topic'),
        ]),
        createDay(4, 'Redis Setup', [
          createItem('Redis Setup', 'topic'),
          createItem('SET/GET', 'topic'),
          createItem('Expiration', 'topic'),
          createItem('Caching API responses', 'topic'),
        ]),
        createDay(5, 'Redis Setup', [
          createItem('Redis Setup', 'topic'),
          createItem('SET/GET', 'topic'),
          createItem('Expiration', 'topic'),
          createItem('Caching API responses', 'topic'),
        ]),
        createDay(6, 'Redis Setup', [
          createItem('Redis Setup', 'topic'),
          createItem('SET/GET', 'topic'),
          createItem('Expiration', 'topic'),
          createItem('Caching API responses', 'topic'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(2, 'Real-time Tracking', [
        createDay(1, 'Socket.io', [
          createItem('Socket.io basics', 'topic'),
          createItem('emitting events', 'topic'),
          createItem('listening for location updates', 'topic'),
          createItem('socket.io react nodejs tutorial real time map', 'search', 'socket.io react nodejs tutorial real time map'),
        ]),
        createDay(2, 'Socket.io', [
          createItem('Socket.io basics', 'topic'),
          createItem('emitting events', 'topic'),
          createItem('listening for location updates', 'topic'),
        ]),
        createDay(3, 'Socket.io', [
          createItem('Socket.io basics', 'topic'),
          createItem('emitting events', 'topic'),
          createItem('listening for location updates', 'topic'),
        ]),
        createDay(4, 'Socket.io', [
          createItem('Socket.io basics', 'topic'),
          createItem('emitting events', 'topic'),
          createItem('listening for location updates', 'topic'),
        ]),
        createDay(5, 'Socket.io', [
          createItem('Socket.io basics', 'topic'),
          createItem('emitting events', 'topic'),
          createItem('listening for location updates', 'topic'),
        ]),
        createDay(6, 'Socket.io', [
          createItem('Socket.io basics', 'topic'),
          createItem('emitting events', 'topic'),
          createItem('listening for location updates', 'topic'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(3, 'Payments & Testing', [
        createDay(1, 'Testing Strategies & TDD', [
          createItem('Test-Driven Development (TDD) Approach', 'topic'),
          createItem('Unit vs Integration vs E2E Tests', 'topic'),
          createItem('Test Pyramid', 'topic'),
          createItem('Mocking Strategies', 'topic'),
          createItem('tdd nodejs tutorial', 'search', 'tdd nodejs tutorial'),
          createItem('testing pyramid explained', 'search', 'testing pyramid explained'),
          createItem('jest mocking strategies', 'search', 'jest mocking strategies'),
        ]),
        createDay(2, 'Testing Strategies & TDD', [
          createItem('Test-Driven Development (TDD) Approach', 'topic'),
          createItem('Unit vs Integration vs E2E Tests', 'topic'),
          createItem('Test Pyramid', 'topic'),
          createItem('Mocking Strategies', 'topic'),
        ]),
        createDay(3, 'Payments Integration & Testing', [
          createItem('SSLCommerz/Stripe Integration', 'topic'),
          createItem('Webhook Handling', 'topic'),
          createItem('Testing Payment Flows', 'topic'),
          createItem('Mocking Payment APIs', 'topic'),
          createItem('sslcommerz nodejs integration', 'search', 'sslcommerz nodejs integration'),
          createItem('stripe webhook testing', 'search', 'stripe webhook testing'),
          createItem('mocking payment apis jest', 'search', 'mocking payment apis jest'),
        ]),
        createDay(4, 'Payments Integration & Testing', [
          createItem('SSLCommerz/Stripe Integration', 'topic'),
          createItem('Webhook Handling', 'topic'),
          createItem('Testing Payment Flows', 'topic'),
          createItem('Mocking Payment APIs', 'topic'),
        ]),
        createDay(5, 'Payments Integration & Testing', [
          createItem('SSLCommerz/Stripe Integration', 'topic'),
          createItem('Webhook Handling', 'topic'),
          createItem('Testing Payment Flows', 'topic'),
          createItem('Mocking Payment APIs', 'topic'),
        ]),
        createDay(6, 'Payments Integration & Testing', [
          createItem('SSLCommerz/Stripe Integration', 'topic'),
          createItem('Webhook Handling', 'topic'),
          createItem('Testing Payment Flows', 'topic'),
          createItem('Mocking Payment APIs', 'topic'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(4, 'Docker', [
        createDay(1, 'Docker Basics & Networking', [
          createItem('Dockerfile creation', 'topic'),
          createItem('Docker Networking', 'topic'),
          createItem('Bridge vs Host Network', 'topic'),
          createItem('Container Communication', 'topic'),
          createItem('docker compose nodejs redis postgres', 'search', 'docker compose nodejs redis postgres'),
          createItem('docker networking tutorial', 'search', 'docker networking tutorial'),
          createItem('docker container communication', 'search', 'docker container communication'),
        ]),
        createDay(2, 'Docker Multi-stage Builds', [
          createItem('Multi-stage Dockerfile', 'topic'),
          createItem('Optimizing Image Size', 'topic'),
          createItem('Build vs Production Stages', 'topic'),
          createItem('Layer Caching', 'topic'),
          createItem('docker multi stage builds nodejs', 'search', 'docker multi stage builds nodejs'),
          createItem('optimize docker image size', 'search', 'optimize docker image size'),
          createItem('docker layer caching', 'search', 'docker layer caching'),
        ]),
        createDay(3, 'Kubernetes Basics', [
          createItem('K8s Architecture', 'topic'),
          createItem('Pods', 'topic'),
          createItem('Deployments', 'topic'),
          createItem('Services', 'topic'),
          createItem('ConfigMaps', 'topic'),
          createItem('Basic kubectl Commands', 'topic'),
          createItem('kubernetes basics tutorial', 'search', 'kubernetes basics tutorial'),
          createItem('kubernetes nodejs deployment', 'search', 'kubernetes nodejs deployment'),
          createItem('kubectl commands cheat sheet', 'search', 'kubectl commands cheat sheet'),
        ]),
        createDay(4, 'Kubernetes Basics', [
          createItem('K8s Architecture', 'topic'),
          createItem('Pods', 'topic'),
          createItem('Deployments', 'topic'),
          createItem('Services', 'topic'),
          createItem('ConfigMaps', 'topic'),
          createItem('Basic kubectl Commands', 'topic'),
        ]),
        createDay(5, 'Kubernetes Basics', [
          createItem('K8s Architecture', 'topic'),
          createItem('Pods', 'topic'),
          createItem('Deployments', 'topic'),
          createItem('Services', 'topic'),
          createItem('ConfigMaps', 'topic'),
          createItem('Basic kubectl Commands', 'topic'),
        ]),
        createDay(6, 'Docker Compose & K8s Practice', [
          createItem('Docker Compose services (App+Redis+DB)', 'project'),
          createItem('Kubernetes Deployment Practice', 'project'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
    ],
  },
  {
    id: 'month-6',
    monthNumber: 6,
    title: 'DevOps & Job Hunt',
    goal: 'Professional Polish and Getting Hired.',
    completed: false,
    weeks: [
      createWeek(1, 'Linux & NGINX', [
        createDay(1, 'Linux & SSH Management', [
          createItem('Linux CLI (ssh, grep, ps, top)', 'topic'),
          createItem('SSH Key Authentication', 'topic'),
          createItem('File Permissions', 'topic'),
          createItem('Process Management', 'topic'),
          createItem('linux basics for developers', 'search', 'linux basics for developers'),
          createItem('ssh key authentication tutorial', 'search', 'ssh key authentication tutorial'),
          createItem('linux file permissions', 'search', 'linux file permissions'),
        ]),
        createDay(2, 'NGINX & Process Managers', [
          createItem('NGINX Configuration (Reverse Proxy, Load Balancing)', 'topic'),
          createItem('PM2 Process Manager', 'topic'),
          createItem('Cluster Mode', 'topic'),
          createItem('Auto-restart', 'topic'),
          createItem('nginx reverse proxy nodejs tutorial', 'search', 'nginx reverse proxy nodejs tutorial'),
          createItem('pm2 process manager', 'search', 'pm2 process manager'),
          createItem('pm2 cluster mode', 'search', 'pm2 cluster mode'),
        ]),
        createDay(3, 'Environment Management', [
          createItem('Managing .env across Servers', 'topic'),
          createItem('Secrets Management', 'topic'),
          createItem('dotenv-vault', 'topic'),
          createItem('AWS Parameter Store/Secrets Manager', 'topic'),
          createItem('nodejs environment variables production', 'search', 'nodejs environment variables production'),
          createItem('secrets management nodejs', 'search', 'secrets management nodejs'),
          createItem('dotenv vault tutorial', 'search', 'dotenv vault tutorial'),
        ]),
        createDay(4, 'NGINX & Process Managers', [
          createItem('NGINX Configuration (Reverse Proxy, Load Balancing)', 'topic'),
          createItem('PM2 Process Manager', 'topic'),
          createItem('Cluster Mode', 'topic'),
          createItem('Auto-restart', 'topic'),
        ]),
        createDay(5, 'Environment Management', [
          createItem('Managing .env across Servers', 'topic'),
          createItem('Secrets Management', 'topic'),
          createItem('dotenv-vault', 'topic'),
          createItem('AWS Parameter Store/Secrets Manager', 'topic'),
        ]),
        createDay(6, 'Review & Rest', []),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(2, 'Monitoring & Documentation', [
        createDay(1, 'Monitoring & Alerting', [
          createItem('Sentry Error Tracking', 'topic'),
          createItem('LogRocket Session Replay', 'topic'),
          createItem('Setting Up Alerts', 'topic'),
          createItem('Slack/Email Notifications', 'topic'),
          createItem('sentry nodejs integration', 'search', 'sentry nodejs integration'),
          createItem('logrocket setup', 'search', 'logrocket setup'),
          createItem('nodejs monitoring alerts', 'search', 'nodejs monitoring alerts'),
        ]),
        createDay(2, 'Performance Monitoring', [
          createItem('New Relic/Datadog APM', 'topic'),
          createItem('Response Time Tracking', 'topic'),
          createItem('Database Query Performance', 'topic'),
          createItem('Memory Leaks', 'topic'),
          createItem('nodejs performance monitoring', 'search', 'nodejs performance monitoring'),
          createItem('apm tools comparison', 'search', 'apm tools comparison'),
          createItem('nodejs memory leak detection', 'search', 'nodejs memory leak detection'),
        ]),
        createDay(3, 'Swagger Documentation', [
          createItem('Swagger/OpenAPI setup', 'topic'),
          createItem('System Architecture Diagrams (Draw.io, Excalidraw)', 'topic'),
          createItem('swagger nodejs express tutorial', 'search', 'swagger nodejs express tutorial'),
          createItem('system architecture diagram tools', 'search', 'system architecture diagram tools'),
        ]),
        createDay(4, 'Monitoring & Alerting', [
          createItem('Sentry Error Tracking', 'topic'),
          createItem('LogRocket Session Replay', 'topic'),
          createItem('Setting Up Alerts', 'topic'),
          createItem('Slack/Email Notifications', 'topic'),
        ]),
        createDay(5, 'Performance Monitoring', [
          createItem('New Relic/Datadog APM', 'topic'),
          createItem('Response Time Tracking', 'topic'),
          createItem('Database Query Performance', 'topic'),
          createItem('Memory Leaks', 'topic'),
        ]),
        createDay(6, 'Swagger Documentation', [
          createItem('Swagger/OpenAPI setup', 'topic'),
          createItem('System Architecture Diagrams (Draw.io, Excalidraw)', 'topic'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(3, 'System Design', [
        createDay(1, 'System Design', [
          createItem('Vertical/Horizontal Scaling', 'topic'),
          createItem('Load Balancers', 'topic'),
          createItem('CAP Theorem', 'topic'),
          createItem('system design primer for beginners', 'search', 'system design primer for beginners'),
        ]),
        createDay(2, 'Database Optimization & Sharding', [
          createItem('Vertical/Horizontal Scaling', 'topic'),
          createItem('Database Sharding', 'topic'),
          createItem('Read Replicas', 'topic'),
          createItem('Load Balancers', 'topic'),
          createItem('database sharding explained', 'search', 'database sharding explained'),
          createItem('postgresql read replicas', 'search', 'postgresql read replicas'),
          createItem('horizontal vs vertical scaling', 'search', 'horizontal vs vertical scaling'),
        ]),
        createDay(3, 'Caching Strategies & Message Queues', [
          createItem('CAP Theorem', 'topic'),
          createItem('Redis Caching Patterns (Cache-aside, Write-through)', 'topic'),
          createItem('Message Queues (Bull, RabbitMQ Basics)', 'topic'),
          createItem('redis caching strategies', 'search', 'redis caching strategies'),
          createItem('bull queue nodejs', 'search', 'bull queue nodejs'),
          createItem('rabbitmq nodejs tutorial', 'search', 'rabbitmq nodejs tutorial'),
        ]),
        createDay(4, 'System Design Patterns', [
          createItem('Microservices vs Monolith', 'topic'),
          createItem('API Gateway Pattern', 'topic'),
          createItem('Circuit Breaker', 'topic'),
          createItem('Event-Driven Architecture', 'topic'),
          createItem('system design patterns backend', 'search', 'system design patterns backend'),
          createItem('api gateway pattern', 'search', 'api gateway pattern'),
          createItem('circuit breaker nodejs', 'search', 'circuit breaker nodejs'),
        ]),
        createDay(5, 'System Design Patterns', [
          createItem('Microservices vs Monolith', 'topic'),
          createItem('API Gateway Pattern', 'topic'),
          createItem('Circuit Breaker', 'topic'),
          createItem('Event-Driven Architecture', 'topic'),
        ]),
        createDay(6, 'System Design Practice', [
          createItem('Design a Scalable System', 'practice'),
          createItem('Architecture Diagrams', 'practice'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
      createWeek(4, 'Job Hunt', [
        createDay(1, 'Job Hunt', [
          createItem('Resume Optimization', 'topic'),
          createItem('LinkedIn Outreach', 'topic'),
          createItem('Applications', 'topic'),
          createItem('backend developer resume tips', 'search', 'backend developer resume tips'),
        ]),
        createDay(2, 'Job Hunt', [
          createItem('Resume Optimization', 'topic'),
          createItem('LinkedIn Outreach', 'topic'),
          createItem('Applications', 'topic'),
        ]),
        createDay(3, 'Job Hunt', [
          createItem('Resume Optimization', 'topic'),
          createItem('LinkedIn Outreach', 'topic'),
          createItem('Applications', 'topic'),
        ]),
        createDay(4, 'Job Hunt', [
          createItem('Resume Optimization', 'topic'),
          createItem('LinkedIn Outreach', 'topic'),
          createItem('Applications', 'topic'),
        ]),
        createDay(5, 'Job Hunt', [
          createItem('Resume Optimization', 'topic'),
          createItem('LinkedIn Outreach', 'topic'),
          createItem('Applications', 'topic'),
        ]),
        createDay(6, 'Job Hunt', [
          createItem('Resume Optimization', 'topic'),
          createItem('LinkedIn Outreach', 'topic'),
          createItem('Applications', 'topic'),
        ]),
        createDay(7, 'Review & Rest', []),
      ]),
    ],
  },
];
